"""stock info

Revision ID: 764c6a72f71
Revises: 18ed5a6a18a1
Create Date: 2014-06-28 21:22:27.030000

"""

# revision identifiers, used by Alembic.
revision = '764c6a72f71'
down_revision = '18ed5a6a18a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('stock', sa.Column('location', sa.String(length=300), nullable=True))
    op.add_column('stock', sa.Column('name', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'name')
    op.drop_column('stock', 'location')
    op.drop_column('stock', 'category')
    ### end Alembic commands ###
