"""added history data

Revision ID: b3bdebc15bb
Revises: 1d9e718e1c9b
Create Date: 2014-08-30 04:12:59.142001

"""

# revision identifiers, used by Alembic.
revision = 'b3bdebc15bb'
down_revision = '1d9e718e1c9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('mean_deviation_10', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('mean_deviation_100', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('mean_deviation_20', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('mean_deviation_5', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('mean_deviation_50', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('p_sma_100_days', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('p_sma_10_days', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('p_sma_20_days', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('p_sma_50_days', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('p_sma_5_days', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('sma_100_days', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('sma_10_days', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('sma_20_days', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('sma_50_days', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('sma_5_days', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'sma_5_days')
    op.drop_column('history', 'sma_50_days')
    op.drop_column('history', 'sma_20_days')
    op.drop_column('history', 'sma_10_days')
    op.drop_column('history', 'sma_100_days')
    op.drop_column('history', 'p_sma_5_days')
    op.drop_column('history', 'p_sma_50_days')
    op.drop_column('history', 'p_sma_20_days')
    op.drop_column('history', 'p_sma_10_days')
    op.drop_column('history', 'p_sma_100_days')
    op.drop_column('history', 'mean_deviation_50')
    op.drop_column('history', 'mean_deviation_5')
    op.drop_column('history', 'mean_deviation_20')
    op.drop_column('history', 'mean_deviation_100')
    op.drop_column('history', 'mean_deviation_10')
    ### end Alembic commands ###
